services:
    mariadb:
        image: mariadb
        ports:
            - 3306:3306
        volumes:
            - ./db/data:/var/lib/mysql
            - ./db/sql:/docker-entrypoint-initdb.d:rw
            - ./db/conf.d:/etc/mysql/conf.d
        environment:
            MYSQL_DATABASE: myt
            MYSQL_USER: mariadb
            MYSQL_PASSWORD: example
            MYSQL_ROOT_PASSWORD: example
            MYSQL_ROOT_HOST: mariadb

